---
kind: pipeline
type: docker
name: Build and test amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Build source
    image: python:3.10
    commands:
    - make build

  - name: Install
    image: python:3.10
    commands:
    - make dist
    - pip3 install -r requirements.txt
    - pip3 install dist/*.whl
#     - pipenv install pytest

#   - name: Run tests
#     image: python:3.10
#     commands:
#       pipenv run pytest

---
kind: pipeline
type: docker
name: Publish package to PyPi

platform:
  os: linux
  arch: amd64

steps:
  - name: Newer version to publish?
    image: python:3.10
    commands:
      - pip3 install delugeClient-kevin -q -q
      - bash publish_version?.sh

  - name: PyPi verify
    image: python3.10
    commands:
      - make dist
      - pip3 install twine
      - twine check dist/*

  - name: PyPi test publish
    image: python3.10
    environment:
      TWINE_USERNAME:
        from_secret: TWINE_USERNAME
      TWINE_PASSWORD:
        from_secret: TWINE_TEST_PASSWORD
    commands:
      - make dist
      - pip3 install twine
      - twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  # - name: PyPi publish
  #   image: python:3.10
  #   environment:
  #     TWINE_USERNAME:
  #       from_secret: TWINE_USERNAME
  #     TWINE_PASSWORD:
  #       from_secret: TWINE_TEST_PASSWORD
  #   commands:
  #     - make dist
  #     - pip3 install twine
  #     - twine upload dist/*

depends_on:
  - Build and test amd64

trigger:
  branch:
    - master
    - ci/pypi-publish-by-token
  event:
    exclude:
      - pull_request

---
kind: signature
hmac: f0bcccc150938c350ff774024538d6d4c7da56ce6724e16f36fb177709cc15a0

...
